apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: kube-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ubuntuhelm.esc.yipintsoigroup.com/docker/demo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080